export const ATTACK_WITH_WEAPON = "ATTACK_WITH_WEAPON";

export const CAST_CANTRIP = "CAST_CANTRIP"; //TODO
export const CAST_SPELL = "CAST_SPELL"; // TODO

export const ROLL_ABILITY_SCORE = "ROLL_ABILITY_SCORE";
export const ROLL_SAVING_THROW = "ROLL_SAVING_THROW";
export const ROLL_INITIATIVE = "ROLL_INITIATIVE";
export const ROLL_SKILL = "ROLL_SKILL";

export const USE_ACTION = "USE_ACTION";
export const USE_FEATURE = "USE_FEATURE";
